-- Seed data for Golf Shop E-commerce
-- Run this after schema.sql to populate initial data

-- Insert Categories
INSERT INTO categories (name, slug, description, display_order, is_active) VALUES
  ('Clubs', 'clubs', 'Golf clubs including drivers, irons, wedges, and putters', 1, true),
  ('Balls', 'balls', 'Premium golf balls for every skill level', 2, true),
  ('Shoes', 'shoes', 'Golf shoes for comfort and performance on the course', 3, true),
  ('Gloves', 'gloves', 'Golf gloves for better grip and control', 4, true),
  ('Bags', 'bags', 'Golf bags including stand, cart, and travel bags', 5, true),
  ('Accessories', 'accessories', 'Golf accessories including rangefinders, GPS, and training aids', 6, true);

-- Insert Products

-- ==================== CLUBS - DRIVERS ====================

INSERT INTO products (title, brand, price, sale_price, category, subcategory, description, slug, image_url, featured, best_seller, new_arrival, in_stock, stock_quantity, rating, review_count, specifications, filters, body_content) VALUES
(
  'Titleist TSi3 Driver',
  'Titleist',
  599.99,
  499.99,
  'clubs',
  'drivers',
  'The TSi3 driver combines speed with precision, featuring an adjustable weight system for customized performance.',
  'titleist-tsi3-driver',
  'http://localhost:5065/images/products/TitleistTSi3Driver.png',
  true,
  true,
  false,
  true,
  15,
  4.8,
  245,
  '{"clubType": "Driver", "loft": "9°, 10°", "shaftMaterial": "Graphite", "hand": "Right, Left", "gender": "Men''s"}',
  '{"clubType": "Drivers", "hand": ["Right", "Left"], "gender": "Men''s", "shaftMaterial": "Graphite", "shaftFlex": ["Stiff", "Regular"], "skillLevel": ["Intermediate", "Advanced", "Professional"]}',
  'Tour-proven driver delivering exceptional speed and adjustability with SureFit CG and ATI 425 Aerospace Titanium face.'
),
(
  'TaylorMade Stealth 2 Driver',
  'TaylorMade',
  599.99,
  NULL,
  'clubs',
  'drivers',
  'Revolutionary carbon face technology provides enhanced energy transfer for explosive distance and forgiveness.',
  'taylormade-stealth-2-driver',
  'http://localhost:5065/images/products/TaylorMadeStealth2Driver.png',
  true,
  true,
  true,
  true,
  12,
  4.9,
  387,
  '{"clubType": "Driver", "loft": "9°, 10.5°, 12°", "shaftMaterial": "Graphite", "hand": "Right, Left", "gender": "Men''s"}',
  '{"clubType": "Drivers", "hand": ["Right", "Left"], "gender": "Men''s", "shaftMaterial": "Graphite", "shaftFlex": ["Stiff", "Regular", "Senior"], "skillLevel": ["Beginner", "Intermediate", "Advanced"]}',
  '60X Carbon Twist Face and advanced aerodynamics deliver maximum ball speed and forgiveness across the entire face.'
),
(
  'Callaway Paradym Driver',
  'Callaway',
  579.99,
  529.99,
  'clubs',
  'drivers',
  'Shift your performance paradigm with the new Paradym Driver featuring advanced 360 Carbon Chassis.',
  'callaway-paradym-driver',
  'http://localhost:5065/images/products/CallawayParadymDriver.png',
  true,
  false,
  false,
  true,
  18,
  4.7,
  256,
  '{"clubType": "Driver", "loft": "9°, 10.5°", "shaftMaterial": "Graphite", "hand": "Right", "gender": "Men''s"}',
  '{"clubType": "Drivers", "hand": "Right", "gender": "Men''s", "shaftMaterial": "Graphite", "shaftFlex": ["Stiff", "Regular"], "skillLevel": ["Intermediate", "Advanced"]}',
  'Industry-first 360 Carbon Chassis and AI-designed Jailbreak Speed Frame deliver exceptional distance and stability.'
),

-- ==================== CLUBS - IRONS ====================

(
  'Callaway Rogue ST Max Irons',
  'Callaway',
  899.99,
  NULL,
  'clubs',
  'irons',
  'Game improvement irons with AI-designed Flash Face Cup for increased ball speed and forgiveness.',
  'callaway-rogue-st-irons',
  'http://localhost:5065/images/products/CallawayRogueSTMaxIrons.png',
  true,
  true,
  false,
  true,
  8,
  4.7,
  312,
  '{"clubType": "Irons", "ironGroup": "Complete Set (5-PW, AW)", "ironType": "Game Improvement", "shaftMaterial": "Steel", "hand": "Right", "gender": "Men''s"}',
  '{"clubType": "Irons", "ironGroup": ["Mid Irons", "Short Irons"], "ironType": "Game Improvement", "hand": "Right", "gender": "Men''s", "shaftMaterial": "Steel", "shaftFlex": "Regular", "skillLevel": ["Beginner", "Intermediate"]}',
  'Combines speed, forgiveness, and premium feel with AI Flash Face Cup and tungsten weighting.'
),
(
  'TaylorMade P790 Irons',
  'TaylorMade',
  1299.99,
  1199.99,
  'clubs',
  'irons',
  'Players distance irons combining forged feel with explosive distance through SpeedFoam Air technology.',
  'taylormade-p790-irons',
  'http://localhost:5065/images/products/TaylorMadeP790Irons.png',
  true,
  false,
  true,
  true,
  10,
  4.9,
  421,
  '{"clubType": "Irons", "ironGroup": "Complete Set (4-PW)", "ironType": "Players Distance", "shaftMaterial": "Steel", "hand": "Right, Left", "gender": "Men''s"}',
  '{"clubType": "Irons", "ironGroup": ["Long Irons", "Mid Irons", "Short Irons"], "ironType": "Players Distance", "hand": ["Right", "Left"], "gender": "Men''s", "shaftMaterial": "Steel", "shaftFlex": ["Stiff", "Regular"], "skillLevel": ["Intermediate", "Advanced", "Professional"]}',
  'Forged hollow body construction with SpeedFoam Air and Inverted Cone Technology for elite performance.'
),
(
  'Ping G430 Irons',
  'Ping',
  999.99,
  NULL,
  'clubs',
  'irons',
  'High-launching irons with increased ball speed from new FACEWRAP technology and PurFlex cavity badge.',
  'ping-g430-irons',
  'http://localhost:5065/images/products/PingG430Irons.png',
  false,
  true,
  false,
  true,
  14,
  4.8,
  298,
  '{"clubType": "Irons", "ironGroup": "Complete Set (5-PW, UW)", "ironType": "Game Improvement", "shaftMaterial": "Graphite", "hand": "Right", "gender": "Men''s"}',
  '{"clubType": "Irons", "ironGroup": ["Mid Irons", "Short Irons"], "ironType": "Game Improvement", "hand": "Right", "gender": "Men''s", "shaftMaterial": "Graphite", "shaftFlex": ["Regular", "Senior"], "skillLevel": ["Beginner", "Intermediate"]}',
  'FACEWRAP Technology and lower CG deliver higher launch, increased distance, and improved stopping power.'
),

-- ==================== CLUBS - WEDGES ====================

(
  'Titleist Vokey SM9 Wedge',
  'Titleist',
  179.99,
  NULL,
  'clubs',
  'wedges',
  'Tour-proven wedge with enhanced spin and improved feel for precision short game performance.',
  'vokey-sm9-wedge',
  'http://localhost:5065/images/products/TitleistVokeySM9Wedge.png',
  false,
  true,
  false,
  true,
  22,
  4.9,
  428,
  '{"clubType": "Wedge", "wedgeType": "Sand Wedge", "loft": "56°", "bounce": "10°", "grind": "M Grind", "shaftMaterial": "Steel", "hand": "Right", "gender": "Men''s"}',
  '{"clubType": "Wedges", "wedgeType": "Sand", "loft": "56°", "hand": "Right", "gender": "Men''s", "shaftMaterial": "Steel", "skillLevel": ["Intermediate", "Advanced", "Professional"]}',
  'Ultimate spin, control, and consistency with Progressive CG and TX4 Grooves.'
),
(
  'Cleveland RTX ZipCore Wedge',
  'Cleveland',
  149.99,
  129.99,
  'clubs',
  'wedges',
  'Revolutionary ZipCore technology shifts weight to raise MOI and lower CG for enhanced spin and control.',
  'cleveland-rtx-zipcore-wedge',
  'http://localhost:5065/images/products/ClevelandRTXZipCoreWedge.png',
  true,
  false,
  false,
  true,
  28,
  4.7,
  356,
  '{"clubType": "Wedge", "wedgeType": "Gap Wedge", "loft": "52°", "bounce": "12°", "grind": "Full Grind", "shaftMaterial": "Steel", "hand": "Right, Left", "gender": "Men''s"}',
  '{"clubType": "Wedges", "wedgeType": "Gap", "loft": "52°", "hand": ["Right", "Left"], "gender": "Men''s", "shaftMaterial": "Steel", "skillLevel": ["Beginner", "Intermediate", "Advanced"]}',
  'ZipCore technology and UltiZip Grooves provide maximum spin and consistency from any lie.'
),

-- ==================== CLUBS - PUTTERS ====================

(
  'Scotty Cameron Special Select Newport 2',
  'Titleist',
  449.99,
  NULL,
  'clubs',
  'putters',
  'Classic blade putter with timeless design and Tour-proven performance.',
  'scotty-cameron-newport-2',
  'http://localhost:5065/images/products/ScottyCameronSpecialSelectNewport2.png',
  true,
  true,
  false,
  true,
  16,
  4.9,
  612,
  '{"clubType": "Putter", "putterType": "Blade", "length": "33\", 34\", 35\"", "hand": "Right", "gender": "Unisex"}',
  '{"clubType": "Putters", "putterType": "Blade", "hand": "Right", "skillLevel": ["Intermediate", "Advanced", "Professional"]}',
  'Precision milled from 303 stainless steel with refined weighting for exceptional feel and roll.'
),
(
  'Odyssey White Hot OG Putter',
  'Odyssey',
  199.99,
  NULL,
  'clubs',
  'putters',
  'The legendary White Hot insert returns, delivering incredible feel and consistent roll.',
  'odyssey-white-hot-og',
  'http://localhost:5065/images/products/OdysseyWhiteHotOGPutter.png',
  false,
  true,
  true,
  true,
  24,
  4.8,
  487,
  '{"clubType": "Putter", "putterType": "Mallet", "length": "34\", 35\"", "hand": "Right, Left", "gender": "Unisex"}',
  '{"clubType": "Putters", "putterType": "Mallet", "hand": ["Right", "Left"], "skillLevel": ["Beginner", "Intermediate", "Advanced"]}',
  'Iconic White Hot insert with improved acoustics and feel for confident putting performance.'
),

-- ==================== GOLF BALLS ====================

(
  'Titleist Pro V1 Golf Balls',
  'Titleist',
  54.99,
  NULL,
  'balls',
  NULL,
  'The #1 ball in golf, delivering total performance with exceptional distance, consistent flight, and Drop-and-Stop control.',
  'titleist-pro-v1',
  'http://localhost:5065/images/products/TitleistProV1GolfBalls.png',
  true,
  true,
  false,
  true,
  150,
  4.9,
  892,
  '{"compression": "Medium (87)", "construction": "3-Piece", "coverMaterial": "Urethane", "feel": "Soft", "color": "White"}',
  '{"compression": "Medium (70-85)", "construction": "3-Piece", "coverMaterial": "Urethane", "feel": "Soft", "skillLevel": ["Advanced", "Professional"], "color": "White"}',
  'Tour-level performance with faster core, soft feel, consistent flight, and exceptional greenside spin.'
),
(
  'Callaway Chrome Soft Golf Balls',
  'Callaway',
  49.99,
  NULL,
  'balls',
  NULL,
  'Premium golf ball with exceptional feel and optimized aerodynamics for longer, straighter flight.',
  'callaway-chrome-soft',
  'http://localhost:5065/images/products/CallawayChromeSoftGolfBalls.png',
  true,
  true,
  false,
  true,
  200,
  4.8,
  654,
  '{"compression": "Low (65)", "construction": "3-Piece", "coverMaterial": "Urethane", "feel": "Soft", "color": "White"}',
  '{"compression": "Low (45-70)", "construction": "3-Piece", "coverMaterial": "Urethane", "feel": "Soft", "skillLevel": ["Intermediate", "Advanced"], "color": "White"}',
  'Combines tour-level performance with soft feel using Hyper Elastic SoftFast Core technology.'
),
(
  'TaylorMade TP5 Golf Balls',
  'TaylorMade',
  54.99,
  49.99,
  'balls',
  NULL,
  'Complete tee-to-green performance with 5-layer construction and Tour Flight Dimple Pattern.',
  'taylormade-tp5',
  'http://localhost:5065/images/products/TaylorMadeTP5GolfBalls.png',
  true,
  false,
  true,
  true,
  180,
  4.9,
  743,
  '{"compression": "High (97)", "construction": "5-Piece", "coverMaterial": "Urethane", "feel": "Medium", "color": "White"}',
  '{"compression": "High (86+)", "construction": "5-Piece", "coverMaterial": "Urethane", "feel": "Medium", "skillLevel": ["Advanced", "Professional"], "color": "White"}',
  '5-layer construction provides complete performance with increased speed, higher launch, and exceptional greenside control.'
),
(
  'Bridgestone Tour B XS Golf Balls',
  'Bridgestone',
  49.99,
  NULL,
  'balls',
  NULL,
  'Tiger''s choice. Premium tour ball engineered for increased ball speed and enhanced greenside spin.',
  'bridgestone-tour-b-xs',
  'http://localhost:5065/images/products/BridgestoneTourBXSGolfBalls.png',
  false,
  true,
  false,
  true,
  120,
  4.8,
  521,
  '{"compression": "Medium (88)", "construction": "3-Piece", "coverMaterial": "Urethane", "feel": "Soft", "color": "White"}',
  '{"compression": "Medium (70-85)", "construction": "3-Piece", "coverMaterial": "Urethane", "feel": "Soft", "skillLevel": ["Intermediate", "Advanced", "Professional"], "color": "White"}',
  'ReactIV urethane cover and gradational compression core deliver Tour-level performance and feel.'
),

-- ==================== SHOES ====================

(
  'FootJoy Pro SL Golf Shoes',
  'FootJoy',
  159.99,
  NULL,
  'shoes',
  'mens',
  'Premium spikeless golf shoes combining tour performance with versatile style.',
  'footjoy-pro-sl',
  'http://localhost:5065/images/products/FootJoyProSLGolfShoes.png',
  true,
  true,
  false,
  true,
  45,
  4.7,
  523,
  '{"spikeType": "Spikeless", "waterproof": "Yes", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  '{"spikeType": "Spikeless", "waterproof": "Yes", "style": "Athletic", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  'Tour-proven performance with Infinity Outsole, OptiFlex technology, and complete waterproof protection.'
),
(
  'Adidas CodeChaos 22 Golf Shoes',
  'Adidas',
  149.99,
  129.99,
  'shoes',
  'mens',
  'Revolutionary spikeless design with Twist Grip outsole for maximum traction and athletic performance.',
  'adidas-codechaos-22',
  'http://localhost:5065/images/products/AdidasCodeChaos22GolfShoes.png',
  true,
  false,
  true,
  true,
  38,
  4.8,
  412,
  '{"spikeType": "Spikeless", "waterproof": "Yes", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  '{"spikeType": "Spikeless", "waterproof": "Yes", "style": "Athletic", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  'Boost cushioning and Twist Grip outsole deliver comfort and performance for 18 holes and beyond.'
),
(
  'Nike Air Zoom Infinity Tour Golf Shoes',
  'Nike',
  179.99,
  NULL,
  'shoes',
  'mens',
  'Premium spiked golf shoes with Zoom Air and React foam for ultimate comfort and stability.',
  'nike-air-zoom-infinity',
  'http://localhost:5065/images/products/NikeAirZoomInfinityTourGolfShoes.png',
  false,
  true,
  false,
  true,
  32,
  4.9,
  567,
  '{"spikeType": "Spiked", "waterproof": "Yes", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  '{"spikeType": "Spiked", "waterproof": "Yes", "style": "Athletic", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  'Tour-level performance with Zoom Air units, React foam, and integrated traction pattern for explosive power.'
),
(
  'Ecco Biom C4 Golf Shoes',
  'Ecco',
  199.99,
  NULL,
  'shoes',
  'mens',
  'Premium leather golf shoes with anatomical fit and groundbreaking MTN GRIP outsole.',
  'ecco-biom-c4',
  'http://localhost:5065/images/products/EccoBiomC4GolfShoes.png',
  true,
  false,
  false,
  true,
  28,
  4.8,
  389,
  '{"spikeType": "Spikeless", "waterproof": "Yes", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  '{"spikeType": "Spikeless", "waterproof": "Yes", "style": "Classic", "closure": "Laces", "width": "Standard", "gender": "Men''s"}',
  'Premium yak leather upper with GORE-TEX waterproofing and anatomical last for natural movement.'
),

-- ==================== GLOVES ====================

(
  'Titleist Perma-Soft Golf Glove',
  'Titleist',
  22.99,
  NULL,
  'gloves',
  'mens',
  'Premium cabretta leather glove offering exceptional feel, grip, and durability.',
  'titleist-permasoft',
  'http://localhost:5065/images/products/TitleistPerma-SoftGolfGlove.png',
  false,
  true,
  false,
  true,
  80,
  4.8,
  734,
  '{"material": "Cabretta Leather", "leatherGrade": "AAA", "weatherType": "All-Weather", "hand": "Left", "gender": "Men''s", "color": "White"}',
  '{"material": "Cabretta Leather", "leatherGrade": "AAA", "weatherType": "All-Weather", "hand": "Left", "gender": "Men''s"}',
  'AAA-grade cabretta leather with FiberSof technology for superior feel and performance in all conditions.'
),
(
  'FootJoy StaSof Golf Glove',
  'FootJoy',
  19.99,
  NULL,
  'gloves',
  'mens',
  'Premium cabretta leather glove with exclusive Taction2 Advanced Performance leather.',
  'footjoy-stasof',
  'http://localhost:5065/images/products/FootJoyStaSofGolfGlove.png',
  false,
  true,
  false,
  true,
  95,
  4.7,
  892,
  '{"material": "Cabretta Leather", "leatherGrade": "AAA", "weatherType": "Dry Weather", "hand": "Left", "gender": "Men''s", "color": "White"}',
  '{"material": "Cabretta Leather", "leatherGrade": "AAA", "weatherType": "Dry Weather", "hand": "Left", "gender": "Men''s"}',
  '#1 glove in golf with exclusive Taction2 leather for unmatched softness, grip, and durability.'
),

-- ==================== BAGS ====================

(
  'Titleist Players 4 StaDry Stand Bag',
  'Titleist',
  299.99,
  269.99,
  'bags',
  'stand',
  'Premium waterproof stand bag with 4-way top and innovative StaDry pocket system.',
  'titleist-players-4-stadry',
  'http://localhost:5065/images/products/TitleistPlayers4StaDryStandBag.png',
  true,
  true,
  false,
  true,
  22,
  4.9,
  345,
  '{"bagType": "Stand Bag", "dividers": "4-Way Top", "pockets": "8", "waterproof": "Yes", "weight": "5.5 lbs"}',
  '{"bagType": "Stand", "dividers": ["4-Way"], "waterproof": "Yes", "pockets": "6-9"}',
  'Tour-inspired design with waterproof StaDry pockets, integrated stand, and premium organization.'
),
(
  'Callaway ORG 14 Cart Bag',
  'Callaway',
  279.99,
  NULL,
  'bags',
  'cart',
  'Premium cart bag with 14-way full-length divider system for ultimate club organization.',
  'callaway-org-14',
  'http://localhost:5065/images/products/CallawayORG14CartBag.png',
  true,
  false,
  false,
  true,
  18,
  4.8,
  478,
  '{"bagType": "Cart Bag", "dividers": "14-Way Full Length", "pockets": "10", "waterproof": "No", "weight": "7.5 lbs"}',
  '{"bagType": "Cart", "dividers": ["14-Way"], "waterproof": "No", "pockets": "10+"}',
  '14-way full-length dividers keep clubs organized and protected with multiple pockets for all your gear.'
),

-- ==================== ACCESSORIES ====================

(
  'Bushnell Pro XE Rangefinder',
  'Bushnell',
  549.99,
  499.99,
  'accessories',
  'rangefinders',
  'Elite rangefinder with slope, wind, and temperature compensation for ultimate accuracy.',
  'bushnell-pro-xe',
  'http://localhost:5065/images/products/BushnellProXERangefinder.png',
  true,
  true,
  true,
  true,
  35,
  4.9,
  623,
  '{"range": "500+ yards", "accuracy": "+/- 0.5 yards", "slope": "Yes", "waterproof": "Yes", "magnification": "7x"}',
  '{"type": "Laser Rangefinder", "slope": "Yes", "waterproof": "Yes", "range": "500+ yards"}',
  'Professional-grade rangefinder with Elements feature provides slope, wind, and temperature adjustments.'
),
(
  'Garmin Approach S62 GPS Watch',
  'Garmin',
  499.99,
  NULL,
  'accessories',
  'gps',
  'Premium GPS golf watch with Virtual Caddie, PlaysLike Distance, and full-color touchscreen.',
  'garmin-approach-s62',
  'http://localhost:5065/images/products/GarminApproachS62GPSWatch.png',
  false,
  false,
  false,
  true,
  42,
  4.8,
  512,
  '{"display": "1.3\" Color Touchscreen", "batteryLife": "20 hours (GPS mode)", "courses": "41,000+ preloaded", "waterproof": "Yes (5 ATM)", "features": "Virtual Caddie, Wind Speed"}',
  '{"type": "GPS Watch", "touchscreen": "Yes", "waterproof": "Yes", "features": ["Virtual Caddie", "PlaysLike Distance"]}',
  'Advanced GPS watch with Virtual Caddie analyzes wind and elevation to suggest optimal club selection.'
);
